### ISSUE TITLE
Test command does not parse dependencies appropriately for the bash run

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos7pw8#27]
When running the test in the image it gets stuck at shallow testing with the following error:

`File not found this might be due to error happened when executing the run.sh: /tmp/tmppzkccul_/bash_output.csv`

But the model was working fine as established in the initial runs.

**Comment by GemmaTuron** [comment]
I can confirm the image works just fine when running the following command:

`ersilia -v fetch eos7pw8 --from_dockerhub --version dev-amd64`

but when trying to run a test on the image I get the above error. Some digging turned out: 
```
17:17:06 | INFO     | Installing conda package: install -c lich -c conda-forge syba=1.0.2.alpha
usage: conda [-h] [-v] [--no-plugins] [-V] COMMAND ...
conda: error: unrecognized arguments: syba=1.0.2.alpha
```

So how the test command is taking and processing this command is the problem. @Abellegese this will need to be fixed, but at least we know what is causing the error (which is a LOT!)
When I run the line directly as a command it does not pop an error

**Comment by Abellegese** [comment]
Thanks @GemmaTuron.

**Comment by Abellegese** [comment]
@GemmaTuron this is fixed in this PR https://github.com/ersilia-os/ersilia/pull/1646.

**Comment by GemmaTuron** [comment]
@Abellegese 

I have tried again but I think the installs are still not working for the building of the image, this is the error when testing the image dev-amd64:
```
Collecting rdkit==2023.03.1
  Downloading rdkit-2023.3.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.9 kB)
Collecting numpy (from rdkit==2023.03.1)
  Downloading numpy-2.2.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
Collecting Pillow (from rdkit==2023.03.1)
  Downloading pillow-11.2.1-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (8.9 kB)
Downloading rdkit-2023.3.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (29.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 29.7/29.7 MB 102.5 MB/s eta 0:00:00
Downloading numpy-2.2.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.4/16.4 MB 198.3 MB/s eta 0:00:00
Downloading pillow-11.2.1-cp310-cp310-manylinux_2_28_x86_64.whl (4.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 189.3 MB/s eta 0:00:00
Installing collected packages: Pillow, numpy, rdkit

Successfully installed Pillow-11.2.1 numpy-2.2.5 rdkit-2023.3.1
Collecting joblib==1.4.2
  Downloading joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Downloading joblib-1.4.2-py3-none-any.whl (301 kB)
Installing collected packages: joblib
Successfully installed joblib-1.4.2
Collecting numpy==1.26.0
  Downloading numpy-1.26.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (58 kB)
Downloading numpy-1.26.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 173.9 MB/s eta 0:00:00
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.2.5
    Uninstalling numpy-2.2.5:
      Successfully uninstalled numpy-2.2.5
Successfully installed numpy-1.26.0
File not found this might be due to error happened when executing the run.sh: /tmp/tmpavngx93a/bash_output.csv
```

The Syba package is not being installed

**Comment by Abellegese** [comment]
Ohh okay sorry @GemmaTuron I will take a look this. Its weird.

**Comment by Abellegese** [comment]
Hi @GemmaTuron I think works fine and this model works with both test command and ersilia-pack. But I don't know why this happened in the image.
```bash

## Package Plan ##

  environment location: /home/ubuntu/miniforge3/envs/eos7pw8

  added / updated specs:
    - syba=1.0.2.alpha


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libpq-17.5                 |       hf590da8_0         2.6 MB  conda-forge
    ------------------------------------------------------------
                                           Total:         2.6 MB

The following NEW packages will be INSTALLED:
  syba               lich/noarch::syba-1.0.2.alpha-py_0 
```

**Comment by Abellegese** [comment]
```bash
(eos7pw8)  bela@legend   ersilia-pack  ↰ main ±  pip show syba
Name: syba
Version: 1.0.2a0
Summary: SYBA
Home-page: https://github.com/lich-uct/syba
Author: Milan Vorsilak
Author-email: UNKNOWN
License: GPL-3.0
Location: /home/ubuntu/miniforge3/envs/eos7pw8/lib/python3.10/site-packages
Requires: 
Required-by: 
```

**Comment by Abellegese** [comment]
The result from the model in test command:
```bash
key,input,syba_score
329930df70e39b10f80bdc30da3c1ae3,COc1ccc(cc1OC1CCCC1)[C@@H]1CNC(=O)C1,52.125150588858
```

**Comment by Abellegese** [comment]
@GemmaTuron this model built successfully.

**Comment by Abellegese** [comment]
@GemmaTuron this model buily successfully. Good to close it
